### ISSUE TITLE
T3 Blog feedback

### ISSUE THREAD

**Issue by TimCannady** [caonayemi/caonayemi.github.io#2]
Hi Christine,

Thanks for sharing your post - T3 Arrays and Hashes. 

My favorite is how thorough you are. You do a great job at welcoming someone to your thought process by slowly bringing them up to speed. For example, you discuss strings and their shortcomings before getting into the "solution." 

My feedback would be to consider a slightly different layout of your code snippets. As it reads now it's pretty conversational - code is injected (interpolated? :P ) into your sentences. This is cool in that it's almost like "reading" code, and this is honestly how we were prompted to write (eg, as if we were describing it to our neighbor). Kudos for that! However I found it a little difficult to switch from reading "sentences" to reading "code", if that makes sense. Perhaps this is why lots of our books tend to separate the two.

Here's an example copy/pasted from the post:

    In Ruby, we assign variables by listing the name followed by an equal sign and the assigned value. For       
    example, greeting = 'Hello, loyal blog readers!' would tell the program that the variable greeting points 
    to the string 'Hello, loyal blog readers!'

And here's a way that might make the same section a little more approachable:

    In Ruby, we assign variables by listing the name followed by an equal signed and the assigned value:

    greeting = "Hello, loyal blog readers!
    ==>"Hello, loyal blog readers"

Again, this might be going against the prompt as it assumes the reader understands symbols like "==>". 

That's my only feedback for now, so awesome work and looking forward to reading more!

**Comment by caonayemi** [comment]
Thanks for your feedback, Tim. This is a very good point. I will definitely
include your feedback into future posts. And if I have some extra time this
week, maybe I'll go back to old posts and try to edit them to be more
readable.

Thanks again!

On Sun, Apr 26, 2015 at 4:06 PM, Tim Cannady <notifications@github.com>
wrote:

> Hi Christine,
>
> Thanks for sharing your post - T3 Arrays and Hashes.
>
> My favorite is how thorough you are. You do a great job at welcoming
> someone to your thought process by slowly bringing them up to speed. For
> example, you discuss strings and their shortcomings before getting into the
> "solution."
>
> My feedback would be to consider a slightly different layout of your code
> snippets. As it reads now it's pretty conversational - code is injected
> (interpolated? :P ) into your sentences. This is cool in that it's almost
> like "reading" code, and this is honestly how we were prompted to write
> (eg, as if we were describing it to our neighbor). Kudos for that! However
> I found it a little difficult to switch from reading "sentences" to reading
> "code", if that makes sense. Perhaps this is why lots of our books tend to
> separate the two.
>
> Here's an example copy/pasted from the post:
>
> In Ruby, we assign variables by listing the name followed by an equal sign and the assigned value. For
> example, greeting = 'Hello, loyal blog readers!' would tell the program that the variable greeting points
> to the string 'Hello, loyal blog readers!'
>
> And here's a way that might make the same section a little more
> approachable:
>
> In Ruby, we assign variables by listing the name followed by an equal signed and the assigned value:
>
> greeting = "Hello, loyal blog readers!
> ==>"Hello, loyal blog readers"
>
> Again, this might be going against the prompt as it assumes the reader
> understands symbols like "==>".
>
> That's my only feedback for now, so awesome work and looking forward to
> reading more!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caonayemi/caonayemi.github.io/issues/2>.
>



-- 
Christine Onayemi
caonayemi@gmail.com
Student
Dev Bootcamp
